### ISSUE TITLE
Backend plugin conflicts

### ISSUE THREAD

**Issue by Adrion** [initbizlab/oc-cumuluscore-plugin#15]
When using plugins that extends User Backend panel Cumulus render it unaccessible. 
(Only by using direct url)

Example : 
 - Install CumulusCore.
 - Install kurtjensen-passage

I don't find where you define Menu items from User panel but you override it instead of extending it like others 
Extended menu example : 

```
Event::listen('backend.menu.extendItems', function ($manager) {
	$manager->addSideMenuItems('RainLab.User', 'user', [
		'usergroups' => [
		'label' => 'rainlab.user::lang.groups.all_groups',
		'icon' => 'icon-group',
		'code' => 'u_groups',
		'owner' => 'RainLab.User',
		'url' => Backend::url('rainlab/user/usergroups'),
	],
	'passage_keys' => [
		'label' => 'kurtjensen.passage::lang.plugin.backend_menu',
		'icon' => 'icon-key',
		'order' => 1001,
		'code' => 'passage',
		'owner' => 'RainLab.User',
		'permissions' => ['kurtjensen.passage.*'],
		'url' => Backend::url('kurtjensen/passage/keys'),
	],
	'variance' => [
		'label' => 'kurtjensen.passage::lang.plugin.backend_variance',
		'icon' => 'icon-key',
		'order' => 1002,
		'code' => 'passage',
		'owner' => 'RainLab.User',
		'permissions' => ['kurtjensen.passage.*'],
		'url' => Backend::url('kurtjensen/passage/variances'),
	],]);
});
```

**Comment by czerwonyd** [comment]
Yes, this have not been an accident. We wanted to have all Cumulus related menu entries in one 'Cumulus' menu entry.

I have fixed it in 1.3.7. version. I decided to add two controllers extending those in `RainLab.User`. This way we can still have one `Cumulus` main menu entry and all related sub menus under it. I have also removed event handler that was removing `rainlab-user-users` main menu entry. This way from version 1.3.7 we will have two almost the same backend menus: `rainlab-user-users` and `initbiz-cumuluscore-users`. They both manage the same model.
