### ISSUE TITLE
installation wont work

### ISSUE THREAD

**Issue by chrisvidal** [initbizlab/oc-cumuluscore-plugin#21]
Trying to install through October CMS plugins marketplace, but it won't install on my OC v446.
any idea what is happening, please?
There is no error. I go through the standard updates plugins form the backend settings page.

**Comment by czerwonyd** [comment]
Hi,

Thanks for your question.

Check the 'manage plugins' tab please in your backend (`/backend/system/updates/manage`), maybe Cumulus is yellow with a lock icon. Then we can be almost certain that there were problems with dependencies. Check if all dependent plugins were installed and let me know how it's going.

Tomasz Strojny

**Comment by chrisvidal** [comment]
thanks for your reply.

the plugin Cumulus is not there as it is the first time I am installing it.

Rainlab.user is already installed. What are the other dependencies?

**Comment by czerwonyd** [comment]
Take a look at the Cumulus page on marketplace: https://octobercms.com/plugin/initbiz-cumuluscore There are all deps listed.

According co `composer.json` by for now those are required:
1. rainlab/user-plugin
1. rainlab/location-plugin
1. rainlab/notify-plugin
1. rainlab/userplus-plugin
1. rainlab/pages-plugin
1. initbiz/oc-initdry-plugin

**Comment by chrisvidal** [comment]
oh got it! I missed the InitDry plugin.
thanks.

**Comment by chrisvidal** [comment]
However I have this exception when I try to associated a plan to a cluster

```
Type error: Argument 2 passed to Initbiz\CumulusCore\Repositories\ClusterFeatureLogRepository::registerClusterFeatures() must be of the type array, null given, called in /Users/christophevidal/Sites/oc-asme/plugins/initbiz/cumuluscore/models/Cluster.php on line 145" on line 108 of /Users/christophevidal/Sites/oc-asme/plugins/initbiz/cumuluscore/repositories/ClusterFeatureLogRepository.php<
```

**Comment by czerwonyd** [comment]
Good to know. Probable cause is that you try to assign plan that has no features. But still, it's a bug, so I will fix it as soon as possible (probably tomorrow).

Try to add any feature to the plan for now and let me know if that helped.

**Comment by czerwonyd** [comment]
Or if you just wanted to test how it works you could use Cumulus Theme with Cumulus Demo plugin as shown in the video [here](https://www.youtube.com/watch?v=Y0-OvGzmP5w). 3 minutes and ready :)

**Comment by czerwonyd** [comment]
As promised the bug is fixed in 2.0.9.

Please let me know what are your impressions and expectations after installing Cumulus. Is there something we can to better or possibly what new features should we provide in new versions?

**Comment by chrisvidal** [comment]
Thanks for this, I appreciate.

I didnt have time to install it over the weekend. My use case is that I have 2 types of user to manage (applicants and judges), so i wanted to try out Cumulus to see if it would serve the purpose.

**Comment by chrisvidal** [comment]
I installed all the plugins and theme in a blank OC installation.
When I am trying to seed the demo with the command:

```
php artisan cumulus:seed
```

I got this exception

```
[Illuminate\Database\QueryException]                                                                       
  SQLSTATE[HY000] [2002] No such file or directory (SQL: select count(*) as aggregate from `initbiz_cumulus  
  core_plans` where `slug` = free) 
```

Any idea what I missed?

**Comment by czerwonyd** [comment]
If you want to write the app in the frontend than Cumulus will definitely help you with your use case.

I saw you used 'projects' to install the theme and the plugins. As far as I know this process is slightly different than installing theme using the method I have shown in the video. While using 'projects' you have to ensure by yourself that every dependency plugin is installed by the 'project'. While installing theme from backend (refer to the video), October by itself cares about the dependencies defined in plugins, so I guess you might try this method if you don't know what deps are defined.

But on the other hand, thanks to you I have found a second bug. This time it was with the Cumulus Theme :) And it was pretty the same you had before. I forgot to add `InITDry` plugin to theme dependency. Sorry about that, everything should work now :)

**Comment by chrisvidal** [comment]
I tried again with installing the theme directly from the OC backend, but i still got the same error when I try to seed the plugins with the console command.

**Comment by czerwonyd** [comment]
The migration fixed.

Where did you change the parameter? If it's reproducible I would love to know what you did to give a note in documentation of Cumulus Demo plugin.

Thanks for help making Cumulus better :)
