### ISSUE TITLE
[Question] Soft deletion

### ISSUE THREAD

**Issue by Adrion** [initbizlab/oc-cumuluscore-plugin#22]
Hi ! 
Is it a choice to doesn't include [softdelete trait](https://octobercms.com/docs/database/traits#soft-deleting) ? 

I'll need it and I'd like to know if I have to extend the model or create a PR for yours 😉

**Comment by czerwonyd** [comment]
Hello,

I just didn't have an occasion to do that, so PR is very welcomed as always :)

It's good idea, so if you could, do it for clusters and plans as well. And I'm not sure how it works for RainLab.Users, but we could also extend User model from Cumulus to use it.

Thanks :)

**Comment by Adrion** [comment]
Rainlab already use softdelete by default
I'll send a PR when it's done :)

I was also thinking about a smart way to delete clusters. For example if a user delete his account and they are no more users in the cluster. We may want to delete empty clusters automatically.
You know GDPR and so on...

**Comment by czerwonyd** [comment]
Sounds good.

I would add a backend setting to enable this. If you decide to do this add a note in README as well please.

Thanks once again, waiting for the PR :)
