### ISSUE TITLE
[Question] - OctoberCMS to SAAS platform

### ISSUE THREAD

**Issue by Astriel** [initbizlab/oc-cumuluscore-plugin#9]
Hello ! 

I'm actually making specifications for a project for a customer of mine. 

I saw your plugin and I think that could help me bootstrap my project. 

I'll have 4 types of profiles on the platform : 
- Customers
- Companies
- Companies manager
- Super administrator

Goal is that each company has its own dashboard and should be able from here to create "one page" to present their activity on the platform customers will be able to browse. 

Companies manager depending on the company location will have a separate dashboard to have an overview on some of the companies.

Super administrator will have an overview on everything. 

I was wondering if such a plugin could help me reach that goal ? As far as I understood  yes.

If this is the case, I can also help improving it.
Would love to discuss with you to have your point of view.

**Comment by czerwonyd** [comment]
Hi,
Sorry for delay.
As far as I understand your requirements - yes :)
Creating a skeleton for the app should be fast enough to just give it a try and check if this is what you are searching for.
